SGO/sgo/entities/Hyperlink.yaml, SGO/sgo/entities/Organization.yaml, SGO/sgo/entities/Role.yaml, SGO/sgo/verbs/associates.yaml, SGO/sgo/verbs/belongs.yaml, SGO/sgo/verbs/connects.yaml, SGO/sgo/verbs/contains.yaml, SGO/sgo/verbs/creates.yaml
The hyperlink entity as discussed here: #188.
Other changes are new connections needed for TabTab (internal inter-object referencing) and adding "any: true" on a couple of Entities. I understand this will be implicit going forwards, so I am happy to revert that change on this request if required.
=> Adding Entity `Hyperlink` and some allowed connections

NTO/Forum/entities/Rating.yaml, NTO/Forum/verbs/rates.yaml
=> Adding Entity `Rating` with the Verb `rates`

NTO/Forum/entities/Invite.yaml, NTO/Forum/entities/Permission.yaml, SGO/sgo/verbs/accepts.yaml, SGO/sgo/verbs/approves.yaml, SGO/sgo/verbs/belongs.yaml, SGO/sgo/verbs/corresponds.yaml, SGO/sgo/verbs/creates.yaml, SGO/sgo/verbs/rejects.yaml, SGO/sgo/verbs/requests.yaml, SGO/sgo/verbs/requires.yaml
=> Added Invite/Permission Entities and connections

SGO/sgo/entities/TaskList.yaml
@plarem could you please review?
=> add indexed attributes

NTO/Automation/entities/AutomationIssue.yaml
@plarem could you please review and merge :)?
=> indexed for issue

NTO/Automation/entities/MARSNode.yaml
@plarem could you please review :)?
=> indexed for marsnode

NTO/Automation/entities/KnowledgeItem.yaml
@plarem could you please review and merge :)
=> add indexed

SGO/sgo/attributes/size.yaml, SGO/sgo/entities/Attachment.yaml
@plarem could you please review and merge :)
=> Size attribute

SGO/sgo/verbs/precedes.yaml, SGO/sgo/verbs/subscribes.yaml
We have restructured our *feeds* in tabtab and need some new connections.
=> Adding connections for restructured feed

NTO/Forum/entities/KnowledgeItemHistory.yaml, SGO/sgo/verbs/assignedTo.yaml, SGO/sgo/verbs/associates.yaml, SGO/sgo/verbs/connects.yaml, SGO/sgo/verbs/creates.yaml, SGO/sgo/verbs/endorses.yaml, SGO/sgo/verbs/relates.yaml, SGO/sgo/verbs/responds.yaml, SGO/sgo/verbs/specifies.yaml, SGO/sgo/verbs/subscribes.yaml
Added container node for ogit/Forum/KnowledgeItem within TabTab for the purpose of tracking changes, forks and revisions, various edges will be moved to this parent node such as Upvotes, Replies, Bookmarks.
Resolves #210
=> Added ogit/Forum/KnowledgeItemHistory

NTO/Forum/entities/Group.yaml, NTO/Forum/entities/Role.yaml, SGO/sgo/verbs/approves.yaml, SGO/sgo/verbs/associates.yaml, SGO/sgo/verbs/belongs.yaml, versioning/version.yaml
Deprecate TabTab application reliance on ogit/Organization and ogit/Role for internal application permission structures. Closes #214
=> Added TabTab based entities for Groups/Roles

NTO/Automation/entities/KnowledgeItem.yaml
Corrected the attributes to their correct internal equivalents
=> Fixed attributes

NTO/Forum/verbs/rates.yaml
Allow `Rating` to connect to `ogit/Forum/KnowledgeItemHistory` and `ogit/Automation/KnowledgeItem` for use within TabTab
=> Update Edges for rates verb

NTO/Forum/entities/Rating.yaml, SGO/sgo/verbs/creates.yaml, SGO/sgo/verbs/endorses.yaml, SGO/sgo/verbs/owns.yaml, SGO/sgo/verbs/responds.yaml
=> Changes for TabTab for content ownership and ratings

SGO/sgo/entities/Task.yaml
https://itautopilot.atlassian.net/browse/AF-1738
=> make Task name indexable

NTO/UserMeta/README.md, NTO/UserMeta/entities/Game.ttl, NTO/UserMeta/verbs/loses.ttl, NTO/UserMeta/verbs/plays.ttl, NTO/UserMeta/verbs/wins.ttl
=> Arago ID Game

NTO/BusinessProcess/entities/Milestone.ttl, NTO/BusinessProcess/entities/Project.ttl, NTO/BusinessProcess/entities/SurveyIteration.ttl, NTO/BusinessProcess/entities/SurveyReply.ttl, SGO/sgo/attributes/placement.ttl, SGO/sgo/attributes/plannedFinishDate.ttl, SGO/sgo/attributes/plannedStartDate.ttl, SGO/sgo/attributes/schedule.ttl, SGO/sgo/attributes/surveyQuestions.ttl, SGO/sgo/verbs/belongs.ttl, SGO/sgo/verbs/consumes.ttl, SGO/sgo/verbs/creates.ttl, SGO/sgo/verbs/manages.ttl, SGO/sgo/verbs/produces.ttl, SGO/sgo/verbs/repliedWith.ttl
We have reworked 	ogit types for 'Bluebird' project. Please review and merge.
=> Ogit types for 'Bluebird' project (v2)

NTO/UserMeta/entities/Question.ttl, NTO/UserMeta/verbs/asks.ttl
=> Add questions to the game

SGO/sgo/entities/Attachment.ttl
In order to support it for Profile Avatars
=> add `accessControl` optional attr to `Attachment`

SGO/sgo/verbs/generates.ttl
Please merge and update the global graph
=> Add organization generates timeseries

NTO/UserMeta/entities/Filter.ttl, SGO/sgo/verbs/defines.ttl
In hiro portal users need to be able to define filters for their preferences in the dashboard
=> User filters

SGO/sgo/entities/Alert.ttl, SGO/sgo/verbs/alerts.ttl, SGO/sgo/verbs/belongs.ttl, SGO/sgo/verbs/contains.ttl, SGO/sgo/verbs/creates.ttl
https://itautopilot.atlassian.net/browse/HP-162
=> Add entities and relationships for alerts

NTO/BusinessProcess/entities/Survey.ttl, NTO/BusinessProcess/entities/SurveyIteration.ttl, SGO/sgo/attributes/position.ttl, SGO/sgo/entities/Organization.ttl, SGO/sgo/entities/Person.ttl
Added optional attributes:
- ogit/phone for ogit/Organization
- ogit/type for ogit/BusinessProcess/Survey
- ogit/status for ogit/BusinessProcess/Survey
- ogit/status for ogit/BusinessProcess/SurveyIteration
Added new optional attributes:
- ogit/position for ogit/Person
Added indexed attributes:
- ogit/name for ogit/Organization
- ogit/description for ogit/Organization
=> Updates for bluebird project

SGO/sgo/verbs/follows.ttl
=> add connection Account -> Account

SGO/sgo/verbs/relates.ttl
`ogit/relates` edge from `ogit/Person` to `ogit/BusinessProcess/SurveyIteration` has been added.
=> Edge from Person to SurveyIteration

SGO/sgo/verbs/belongs.ttl
Added connections:
SurveyIteration - Project
SurveyIteration - Milestone
=> Add connections for SurveyIteration

SGO/sgo/entities/Course.ttl, SGO/sgo/entities/Series.ttl, SGO/sgo/entities/Status.ttl, SGO/sgo/verbs/contains.ttl, SGO/sgo/verbs/relates.ttl, SGO/sgo/verbs/worksOn.ttl
Proposed ontology changes to map information about participation in training courses
=> Training info

NTO/Automation/attributes/lifecycle.ttl, NTO/Automation/entities/MARSNode.ttl
related to "PBL-999 - mars model should be decomissionable"
=> Lifecycle attribute for decommissioning of MARSNodes

NTO/Forum/verbs/mentions.ttl
Closes https://github.com/arago/OGIT/issues/290
=> Add Profile to Profile Mentions

SGO/sgo/verbs/sends.ttl
Add `ogit/sends` edge from `ogit/Software/Application` to `ogit/Notification`
=> Add sends edge from application to notification

SGO/sgo/verbs/tracks.ttl
* Allowed edge 'tracks' between person and timeseries to store app launch history
=> HD-86 Created edge 'tracks'

SGO/sgo/verbs/responds.ttl
Corrected edge for ogit/Forum/Reply -> ogit/responds -> ogit/Forum/WorkflowStep
=> Corrected edge for ogit/responds

SGO/sgo/verbs/assignedTo.ttl
This pull request fixes missing edges used by HIRO Community
=> Add missing Edge Definitions for HIRO Community

SGO/sgo/entities/TermsAndConditions.ttl
=> Rename terms and conditions entity attribute: body -> content

SGO/sgo/verbs/reportedOn.ttl
fixes error from previous merge
=> mars2ogit fixes

SGO/sgo/verbs/forks.ttl
This edge is going to be used for tracking forking history for entities.
Now only for KIs.
=> Create a new edge ogit/forks

SGO/core/attributes/_deleted-by-app.ttl, SGO/core/attributes/_deleted-by.ttl, SGO/core/attributes/_reader.ttl, SGO/core/attributes/_source.ttl, SGO/core/attributes/_v-id.ttl, SGO/sgo/verbs/uses.ttl
ogit/_security-types is still missing, please provide a description
=> Missing internals

.gitignore, NTO/Software/entities/ApplicationReview.ttl, SGO/sgo/verbs/creates.ttl, SGO/sgo/verbs/reviews.ttl, SGO/sgo/verbs/versions.ttl
* Software.ApplicationReview vertex
* Software.ApplicationReview -> creates -> Auth.ApplicationReview
* Software.Application -> reviews -> Auth.Application
* Software.Application -> versions -> Auth.Application
=> HDP: Update `creates`, `versions`,  `reviews` verbs and App review entity

SGO/sgo/verbs/belongs.ttl
=> Add belongs relationship between Account and Person

SGO/sgo/verbs/accepts.ttl
Hello guys. We need users to accept HIRO Developer Portal terms before proceeding to platform.
=> Allow `ogit/Auth/Account` > `ogit/accepts` > `ogit/TermsAndConditions`

NTO/Automation/attributes/issueType.ttl, NTO/Automation/entities/AutomationIssue.ttl
=> Add ogit/Automation/issueType attribute for issues

NTO/Accounting/entities/CompanyEntity.ttl, NTO/Accounting/entities/CompanySpecificCategorization.ttl
Added allowed edge contains from CompanyEntity to CompanySpecificCategorization
Added new entity CompanySpecificCategorization.
Please check and verify the new entity definition for validation.
=> Updated the accounting Namespace

NTO/Automation/attributes/webhook.ttl, NTO/Automation/entities/AutomationIssue.ttl
https://en.wikipedia.org/wiki/Webhook
=>  [automation, issue] add webhook property

NTO/Automation/attributes/parentIssue.ttl, NTO/Automation/attributes/suspendUntil.ttl, NTO/Automation/entities/AutomationIssue.ttl
=> Add ogit/Automation/parentIssue and /suspendUntil definitions

NTO/Schedule/attributes/attendanceStatus.ttl, NTO/Schedule/attributes/isOrganizer.ttl
@KaushikGondaliya currently only HIRO Graph's validation detects this problem
=> Add missing validation-type

NTO/SalesDistribution/attributes/amount.ttl, NTO/SalesDistribution/attributes/customerId.ttl, NTO/SalesDistribution/attributes/deliveryId.ttl, NTO/SalesDistribution/attributes/invoiceDate.ttl, NTO/SalesDistribution/attributes/invoiceId.ttl, NTO/SalesDistribution/attributes/salesOrderId.ttl, NTO/SalesDistribution/attributes/transactionDate.ttl, NTO/SalesDistribution/attributes/valueDate.ttl, NTO/SalesDistribution/entities/Customer.ttl, NTO/SalesDistribution/entities/Delivery.ttl, NTO/SalesDistribution/entities/DeliveryItem.ttl, NTO/SalesDistribution/entities/Invoice.ttl, NTO/SalesDistribution/entities/InvoiceItem.ttl, NTO/SalesDistribution/entities/OpenItem.ttl, NTO/SalesDistribution/entities/Payment.ttl, NTO/SalesDistribution/entities/SalesOrder.ttl, NTO/SalesDistribution/entities/SalesOrderItem.ttl
This is the initial data schema for Sales & Distribution data.
=> Initial Sales and Distribution schema.

NTO/SalesDistribution/entities/Customer.ttl
such an error kills graph ontology load
=> Fix inconsistency @prefix

NTO/Credit/Entities/Contract.ttl, NTO/Credit/Entities/Counterparty.ttl, NTO/Credit/Entities/CounterpartyMutable.ttl, NTO/Credit/Entities/EconomicActivity.ttl, NTO/Credit/Entities/Instrument.ttl, NTO/Credit/Entities/InstrumentMutable.ttl, NTO/Credit/Entities/InstrumentType.ttl, NTO/Credit/Entities/JointLiability.ttl, NTO/Credit/Entities/Protection.ttl, NTO/Credit/Entities/ProtectionMutable.ttl, NTO/Credit/Entities/ProtectionType.ttl, NTO/Credit/Entities/Purpose.ttl, NTO/Credit/Verbs/credits.ttl, NTO/Credit/Verbs/debts.ttl, NTO/Credit/Verbs/desktop.ini, NTO/Credit/Verbs/hasHeadOffice.ttl, NTO/Credit/Verbs/hasImmediateParent.ttl, NTO/Credit/Verbs/hasUltimateParent.ttl, NTO/Credit/Verbs/observes.ttl, NTO/Credit/Verbs/originates.ttl, NTO/Credit/Verbs/secures.ttl, NTO/Credit/Verbs/services.ttl
I have created a credit schema for a demo.
=> Creation of a credit schema

NTO/Factory/attributes/equipmentNumber.ttl, NTO/Factory/entities/Action.ttl, NTO/Factory/entities/Component.ttl, NTO/Factory/entities/Failure.ttl, NTO/Factory/entities/Plant.ttl, SGO/sgo/attributes/duration.ttl, SGO/sgo/attributes/durationUnit.ttl, SGO/sgo/attributes/frequency.ttl
@KaushikGondaliya @viteke please review and merge.
=> Extended the Factory NTO for manufacturing.

SGO/core/attributes/_edge-id.ttl, SGO/core/entities/Node.ttl
=> Update and rename _edge_id.ttl to _edge-id.ttl

SGO/sgo/entities/Comment.ttl
https://www.pivotaltracker.com/story/show/172892372
=> #172892372: Connect comment with Account by edge

SGO/sgo/entities/Attachment.ttl
Attachment-belongs->SaaS/ComponentInstance
=> Add new link

NTO/Automation/entities/KnowledgeItem.ttl
https://www.pivotaltracker.com/story/show/174165777
=> #174165777: Add ogit/_tags attr to KI

NTO/Procurement/attributes/productionOrderId.ttl, NTO/Procurement/attributes/purchaseOrderId.ttl, NTO/Procurement/entities/ProductionOrder.ttl, NTO/Procurement/entities/PurchaseOrder.ttl, NTO/Procurement/entities/PurchaseOrderItem.ttl, NTO/SalesDistribution/attributes/shipmentId.ttl, NTO/SalesDistribution/entities/Equipment.ttl, NTO/SalesDistribution/entities/SalesOrder.ttl, NTO/SalesDistribution/entities/Shipment.ttl, NTO/SalesDistribution/entities/ShipmentItem.ttl
Extending the Sales & Distribution module and introducing Purchase Order and Production Order for procurements.
=> Extending the Sales & Distribution module and introducing Procurement. 

NTO/Auth/entities/Team.ttl
https://www.pivotaltracker.com/story/show/176496197
edge `ogit/approves` connects `ogit/Auth/Team` to `ogit/Automation/KnowledgeItem`
edge `ogit/rejects` connects `ogit/Auth/Team` to `ogit/Automation/KnowledgeItem`
=> 176496197: Allow Team to approve and reject KnowledgeItem

SGO/sgo/attributes/isImmutable.ttl, SGO/sgo/attributes/isPermanent.ttl, SGO/sgo/entities/Timeseries.ttl
Add isImmutable to Timeseries.ttl
=> Add isImmutable.ttl property

SDF/Automation/change.json, SDF/Automation/event.json, SDF/Automation/incident.json, SDF/Automation/requirement.json
Add sync of free attributes to all SDF objects
Add sourceId to all SDF objects
=> Free att sync

NTO/SaaS/entities/Integration.ttl
Add active flag to integration entity type.
=> Add active flag to integration entity type.

NTO/Advertising/entities/BidAdjustmentGroup.ttl
=> Allowing edge from BidAdjustmentGroup to TargetingDimension

NTO/Advertising/entities/BidAdjustment.ttl, NTO/Advertising/entities/BidAdjustmentGroup.ttl
=> Change edge types for Advertising

NTO/RL/entities/LearningStatistics.ttl
=> Add attributes to the entity.

NTO/ML/attributes/sourceDataFromTime.ttl, NTO/ML/attributes/sourceDataToTime.ttl, NTO/ML/entities/TrainingData.ttl
=> more attributes to TrainingData entity

NTO/ML/attributes/testSummary.ttl, NTO/ML/attributes/testedOn.ttl, NTO/ML/entities/TrainedModel.ttl
=> add attributes to ML namespace supporting test workflow

NTO/SaaS/entities/Deployment.ttl
=> allow optional name for deployment

SDF/sdf.json
=> Add sdf.json for DoAPI Rest

singleTTL.sh
=> Fix single file generation

SGO/sgo/entities/Organization.ttl
=> Add ogit/tenantId to ogit/Organization

SGO/sgo/entities/Agent.ttl
=> Add ogit/belongs from Agent to Organization

NTO/CustomerSupport/entities/Group.ttl, NTO/CustomerSupport/entities/Organization.ttl, NTO/ServiceManagement/entities/Ticket.ttl
=> Support improvements

SGO/sgo/entities/Attachment.ttl
=> Add tenantId to Attachment

NTO/Automation/entities/DynamicEngineData.ttl
=> Allow DynamicEngineData to belong to ServiceManagement Tickets

NTO/Politics/attributes/legislation.ttl, NTO/Politics/entities/AgendaItem.ttl, NTO/Politics/entities/DisciplinaryMeasure.ttl, NTO/Politics/entities/Discussion.ttl, NTO/Politics/entities/Mandate.ttl, NTO/Politics/entities/Position.ttl, NTO/Politics/entities/Reaction.ttl, SGO/sgo/attributes/endedAt.ttl, SGO/sgo/entities/Event.ttl, SGO/sgo/entities/Organization.ttl, SGO/sgo/entities/Person.ttl, SGO/sgo/verbs/holds.ttl, SGO/sgo/verbs/isMemberOf.ttl, SGO/sgo/verbs/isPresent.ttl
=> New Realm Politics

NTO/Politics/entities/Reaction.ttl
=> PoliticsRealm Reaction trigger

NTO/Politics/entities/DisciplinaryMeasure.ttl, NTO/Politics/entities/Mandate.ttl, NTO/Politics/entities/Reaction.ttl, SGO/sgo/attributes/birthplace.ttl, SGO/sgo/attributes/dateOfDeath.ttl, SGO/sgo/attributes/numberOfChildren.ttl, SGO/sgo/attributes/profession.ttl, SGO/sgo/entities/Person.ttl, SGO/sgo/entities/religion.ttl
=> Extending the politics realm

.gitignore, NTO/Accounting/entities/LineItem.ttl, SGO/sgo/entities/Contract.ttl
@cy303 this PR adds some relations requires for interconnecting existing nodes in the project timetracking domain.
=> Add some relations for timetracking

NTO/ServiceManagement/entities/AccountingRule.ttl, SGO/sgo/attributes/lowerLimit.ttl, SGO/sgo/attributes/upperLimit.ttl
=> Add AccountingRule

NTO/Botany/entities/WoodLog.ttl, SGO/sgo/entities/Attachment.ttl, SGO/sgo/entities/Feature.ttl
=> Extend allowed edges for Botany realm

SGO/sgo/entities/Annotation.ttl
Add reason attribute to Annotation entity to be able to specify a reason for its denial
=> Add reason attribute to Annotation entity

NTO/Botany/entities/WoodLog.ttl
Add optional attribute ogit:name
=> Add optional attribute

SGO/sgo/entities/Event.ttl, SGO/sgo/entities/RoleAssignment.ttl, SGO/sgo/verbs/registers.ttl
=> Add RoleAssignment and Event -registers-> Organization
